SHELL_NAME='bash'

if [ -z "$PS1" ]; then
    return
fi

### load local conf
if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi


if [ -f ~/dotfiles/posix_shell/common/commonrc ]; then
    . ~/dotfiles/posix_shell/common/commonrc
else
    echo "~/dotfiles/posix_shell/common/commonrc : No such file"
fi

if [ -f ~/dotfiles/posix_shell/bash/environments ]; then
    . ~/dotfiles/posix_shell/bash/environments
else
    echo "~/dotfiles/posix_shell/bash/environments : No such file"
fi

if [ -f ~/dotfiles/git/git-completion.bash ]; then
    . ~/dotfiles/git/git-completion.bash
else
    echo "~/dotfiles/git/git-completion.bash : No such file"
fi
if [ -f ~/dotfiles/docker/docker.bash ]; then
    . ~/dotfiles/docker/docker.bash
else
    echo "~/dotfiles/docker/docker.bash : No such file"
fi


PS1="\n\$(shell_info)\n\$(-bashIconWriter)\$(-envWriter)\$ "
