SHELL_NAME='bash'

if [ -z "$PS1" ]; then
    return
fi

### load local conf
if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi


if [ -f ~/dotfiles/posix_shell/common/commonrc ]; then
    . ~/dotfiles/posix_shell/common/commonrc
else
    echo "~/dotfiles/posix_shell/common/commonrc : No such file"
fi

if [ -f ~/dotfiles/posix_shell/bash/environments ]; then
    . ~/dotfiles/posix_shell/bash/environments
else
    echo "~/dotfiles/posix_shell/bash/environments : No such file"
fi

if [ -f ~/.bash/completion/git-completion.bash ]; then
    . ~/.bash/completion/git-completion.bash
else
    echo "~/.bash/completion/git-completion.bash : No such file"
fi
if [ -f ~/.bash/completion/docker ]; then
    . ~/.bash/completion/docker
else
    echo "~/.bash/completion/docker : No such file"
fi

PS1="\n\$(shell_info)\n\$(-bashIconWriter)\$(-envWriter)\$ "
