### ------------ ###
### change shell ###
### ------------ ###

if [ $(echo $SHELL | xargs basename) = 'bash' ]; then
    which zsh >/dev/null 2>&1
    if [ $? = 0 ]; then
        exec zsh
    fi
fi



### ------------------ ###
### shell environments ###
### ------------------ ###

SHELL_NAME='bash'

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
else
    mkdir -p ${HOME}/.bash
    echo "$(date '+%Y/%m/%d_%H:%M:%S')    ~/.bashrc : No such file" \
    >> ${HOME}/.bash/bashrc_err.log
fi
