SHELL_NAME='bash'

if [ -z "$PS1" ]; then
    return
fi

### load local conf
if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi


if [ -f ~/dotfiles/posix_shell/common/commonrc ]; then
    . ~/dotfiles/posix_shell/common/commonrc
else
    echo "~/dotfiles/posix_shell/common/commonrc : No such file"
fi


if [ -f ~/dotfiles/git/git-completion.bash ]; then
    . ~/dotfiles/git/git-completion.bash
else
    echo "~/dotfiles/git/git-completion.bash : No such file"
fi
if [ -f ~/dotfiles/docker/docker.bash ]; then
    . ~/dotfiles/docker/docker.bash
else
    echo "~/dotfiles/docker/docker.bash : No such file"
fi


# gcloud
if [ -f ~/google-cloud-sdk/path.bash.inc ]; then
    . ~/google-cloud-sdk/path.bash.inc
else
    echo "~/google-cloud-sdk/path.bash.inc : No such file"
fi

# gcloud
if [ -f ~/google-cloud-sdk/completion.bash.inc ]; then
    . ~/google-cloud-sdk/completion.bash.inc
else
    echo "~/google-cloud-sdk/completion.bash.inc : No such file"
fi

PS1="\n\$(shell_info)\n\$(-bashIconWriter)\$(-envWriter)\$ "
