### ------------------ ###
### shell environments ###
### ------------------ ###

SHELL_NAME='zsh'

if [ -f ~/.zshrc ]; then
    :
    # . ~/.zshrc
else
    mkdir -p ${HOME}/.bash
    echo "$(date '+%Y/%m/%d_%H:%M:%S')    ~/.zshrc : No such file" \
    >> ${HOME}/.zsh/zshrc_err.log
fi
