SHELL_NAME='bash'

if [ $(echo $SHELL | xargs basename) = 'bash' ]; then
    $(which zsh >/dev/null 2>&1)
    if [ $? = 0 ]; then
        exec zsh
    fi
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
else
    echo "~/.bashrc : No such file"
fi
