if [ -z "$PS1" ]; then
    return
fi

### load local conf
if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi


### directory check
if [ ! -d "$HOME/.ssh" ]; then
    mkdir ${HOME}/.ssh && echo "$HOME/.ssh was created."
fi

if [ ! -d "$HOME/.ssh/local_conf" ]; then
    mkdir ${HOME}/.ssh/local_conf && echo "$HOME/.ssh/local_conf was created."
fi

if [ ! -d "$HOME/.ssh/controlmaster" ] && [ "${SSH_CONNECTION}" = "" ]; then
    mkdir ${HOME}/.ssh/controlmaster && echo "$HOME/.ssh/controlmaster was created."
fi

if [ ! -d "$HOME/bin" ] ; then
    mkdir ${HOME}/bin && \
    echo "$HOME/bin was created."
fi
for path_name in $( find ~/bin -maxdepth 1 -type d -or -type l -not -name '.*' ); do
    if [ ! "$( echo $PATH | grep ${path_name} )" ]; then
        PATH="${path_name}:$PATH"
    fi
    export PATH
done


### load config files
if [ ! -d ~/dotfiles ]; then
    echo "~/dotfiles : No such directory"
fi

if [ -f ~/dotfiles/bash/environments ]; then
    . ~/dotfiles/bash/environments
else
    echo "~/dotfiles/bash/environments : No such file"
fi

if [ -f ~/dotfiles/bash/prompt_script.sh ]; then
    . ~/dotfiles/bash/prompt_script.sh
else
    echo "~/dotfiles/bash/prompt_script.sh : No such file"
fi

if [ -f ~/dotfiles/bash/aliases ]; then
    . ~/dotfiles/bash/aliases
else
    echo "~/dotfiles/bash/aliases : No such file"
fi

if [ -f ~/dotfiles/bash/bash_script.sh ]; then
    . ~/dotfiles/bash/bash_script.sh
else
    echo "~/dotfiles/bash/bash_script.sh : No such file"
fi

if [ -f ~/dotfiles/bash/cmd_wrapper.sh ]; then
    . ~/dotfiles/bash/cmd_wrapper.sh
else
    echo "~/dotfiles/bash/cmd_wrapper.sh : No such file"
fi

if [ -f ~/dotfiles/bash/bash_script_dupbin.sh ]; then
    . ~/dotfiles/bash/bash_script_dupbin.sh
else
    echo "~/dotfiles/bash/bash_script_dupbin.sh : No such file"
fi

if [ -f ~/dotfiles/git/git-completion.bash ]; then
    . ~/dotfiles/git/git-completion.bash
else
    echo "~/dotfiles/git/git-completion.bash : No such file"
fi

if [ -f ~/dotfiles/docker/docker.bash ]; then
    . ~/dotfiles/docker/docker.bash
else
    echo "~/dotfiles/docker/docker.bash : No such file"
fi


# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/google-cloud-sdk/path.bash.inc' ]; then
    . '~/google-cloud-sdk/path.bash.inc'
else
    echo "~/google-cloud-sdk/path.bash.inc : No such file"
fi

# The next line enables shell command completion for gcloud.
if [ -f '~/google-cloud-sdk/completion.bash.inc' ]; then
    . '~/google-cloud-sdk/completion.bash.inc';
else
    echo "~/google-cloud-sdk/completion.bash.inc : No such file"
fi

PS1="\n\$(shell_info)\n\$(-bashIconWriter)\$(-envWriter)\$ "

# command to be executed only the first time
-blankLinePrinter
-sshScreenStarter
-screenStatusPrinter
-dir_status
