SHELL_NAME="bash"

# if [ -f ~/.bashrc ]; then
#     . ~/.bashrc
# else
#     echo "~/.bashrc : No such file"
# fi

if [ $(echo $SHELL | xargs basename) = 'zsh' ]; then
    $(which fish >/dev/null 2>&1)
    if [ $? = 0 ]; then
        exec zsh
    fi
fi
