if [ $(echo $SHELL | xargs basename) = 'bash' ]; then
    $(which fish >/dev/null 2>&1)
    if [ $? = 0 ]; then
        exec fish
    fi
fi

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
else
    echo "~/.bashrc : No such file"
fi
